config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :purchase_orders
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

   root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:supplier_name, :supplier_code, :date, :location, :Total_payment)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :category, :unit_price, :selling_price, :vat, :date, :quantity)
    end
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: [:show, :edit, :update, :destroy]

  # GET /purchase_orders
  # GET /purchase_orders.json
  def index
    @purchase_orders = PurchaseOrder.all
  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
  end

  # GET /purchase_orders/new
  def new
    @purchase_order = PurchaseOrder.new
  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_order }
      else
        format.html { render :new }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1
  # PATCH/PUT /purchase_orders/1.json
  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase_order }
      else
        format.html { render :edit }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    @purchase_order.destroy
    respond_to do |format|
      format.html { redirect_to purchase_orders_url, notice: 'Purchase order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_order_params
      params.require(:purchase_order).permit(:product_name, :product_type, :unit_price, :quantity, :supplier_name, :supplier_code, :date, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/home/index.html.erb
<h1>Welcome to Our sites</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pro</title>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">

        <h1>Welcome to the Sample App</h1>


        <nav>
          <ul class="nav pull-right">
            <li><%= link_to "Home", '#' %></li>
            <li><%= link_to "Managing System",  '#' %></li>
            <li><%= link_to "Product list", '#' %></li>
            <li><%= link_to "Supplier", '#' %></li>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div class="container">
    <%= yield %>
    </div>
  <div class="center hero-unit">

    </div>
  <img alt="Rails" src="/assets/Ims.PNG" />
  <img alt="Rails" src="/assets/pic2.png" />
  <img alt="Rails" src="/assets/email.png" />
  <img alt="Rails" src="/assets/Febu.jpg" />
  <img alt="Rails" src="/assets/google.jpg" />
  <img alt="Rails" src="/assets/googleplay.jpg" />

  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :supplier_name %>
    <%= form.text_field :supplier_name, id: :payment_supplier_name %>
  </div>

  <div class="field">
    <%= form.label :supplier_code %>
    <%= form.number_field :supplier_code, id: :payment_supplier_code %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :payment_date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :payment_location %>
  </div>

  <div class="field">
    <%= form.label :Total_payment %>
    <%= form.text_field :Total_payment, id: :payment_Total_payment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Supplier name</th>
      <th>Supplier code</th>
      <th>Date</th>
      <th>Location</th>
      <th>Total payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.supplier_name %></td>
        <td><%= payment.supplier_code %></td>
        <td><%= payment.date %></td>
        <td><%= payment.location %></td>
        <td><%= payment.Total_payment %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier name:</strong>
  <%= @payment.supplier_name %>
</p>

<p>
  <strong>Supplier code:</strong>
  <%= @payment.supplier_code %>
</p>

<p>
  <strong>Date:</strong>
  <%= @payment.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @payment.location %>
</p>

<p>
  <strong>Total payment:</strong>
  <%= @payment.Total_payment %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :product_product_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :product_category %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.text_field :unit_price, id: :product_unit_price %>
  </div>

  <div class="field">
    <%= form.label :selling_price %>
    <%= form.text_field :selling_price, id: :product_selling_price %>
  </div>

  <div class="field">
    <%= form.label :vat %>
    <%= form.text_field :vat, id: :product_vat %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :product_date %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Category</th>
      <th>Unit price</th>
      <th>Selling price</th>
      <th>Vat</th>
      <th>Date</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.category %></td>
        <td><%= product.unit_price %></td>
        <td><%= product.selling_price %></td>
        <td><%= product.vat %></td>
        <td><%= product.date %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @product.unit_price %>
</p>

<p>
  <strong>Selling price:</strong>
  <%= @product.selling_price %>
</p>

<p>
  <strong>Vat:</strong>
  <%= @product.vat %>
</p>

<p>
  <strong>Date:</strong>
  <%= @product.date %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/purchase_orders/_form.html.erb
<%= form_with(model: purchase_order, local: true) do |form| %>
  <% if purchase_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
      <% purchase_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, id: :purchase_order_product_name %>
  </div>

  <div class="field">
    <%= form.label :product_type %>
    <%= form.text_field :product_type, id: :purchase_order_product_type %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.text_field :unit_price, id: :purchase_order_unit_price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity, id: :purchase_order_quantity %>
  </div>

  <div class="field">
    <%= form.label :supplier_name %>
    <%= form.text_field :supplier_name, id: :purchase_order_supplier_name %>
  </div>

  <div class="field">
    <%= form.label :supplier_code %>
    <%= form.number_field :supplier_code, id: :purchase_order_supplier_code %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :purchase_order_date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :purchase_order_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/purchase_orders/edit.html.erb
<h1>Editing Purchase Order</h1>

<%= render 'form', purchase_order: @purchase_order %>

<%= link_to 'Show', @purchase_order %> |
<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchase Orders</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product type</th>
      <th>Unit price</th>
      <th>Quantity</th>
      <th>Supplier name</th>
      <th>Supplier code</th>
      <th>Date</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_orders.each do |purchase_order| %>
      <tr>
        <td><%= purchase_order.product_name %></td>
        <td><%= purchase_order.product_type %></td>
        <td><%= purchase_order.unit_price %></td>
        <td><%= purchase_order.quantity %></td>
        <td><%= purchase_order.supplier_name %></td>
        <td><%= purchase_order.supplier_code %></td>
        <td><%= purchase_order.date %></td>
        <td><%= purchase_order.location %></td>
        <td><%= link_to 'Show', purchase_order %></td>
        <td><%= link_to 'Edit', edit_purchase_order_path(purchase_order) %></td>
        <td><%= link_to 'Destroy', purchase_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase Order', new_purchase_order_path %>

app/views/purchase_orders/new.html.erb
<h1>New Purchase Order</h1>

<%= render 'form', purchase_order: @purchase_order %>

<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @purchase_order.product_name %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @purchase_order.product_type %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @purchase_order.unit_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @purchase_order.quantity %>
</p>

<p>
  <strong>Supplier name:</strong>
  <%= @purchase_order.supplier_name %>
</p>

<p>
  <strong>Supplier code:</strong>
  <%= @purchase_order.supplier_code %>
</p>

<p>
  <strong>Date:</strong>
  <%= @purchase_order.date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @purchase_order.location %>
</p>

<%= link_to 'Edit', edit_purchase_order_path(@purchase_order) %> |
<%= link_to 'Back', purchase_orders_path %>